services:
    app:
        build: 
            context: ./
            dockerfile: Dockerfile
        container_name: library-dev-app
        restart: unless-stopped
        volumes:
            - .:/workdir
            - /workdir/laravel-app/node_modules  # node_modulesを除外
            - /workdir/laravel-app/vendor       # vendorを除外
        ports:
            - "5174:5174"  # Vite開発サーバー用
        depends_on:
            - db
            - redis
            - mailpit
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - DB_HOST=db
            - DB_DATABASE=library
            - DB_USERNAME=user
            - DB_PASSWORD=password
            - REDIS_HOST=redis
            - MAIL_HOST=mailpit
        networks:
            - library-dev-network
    
    db:
        image: mysql:8.3
        container_name: library-dev-db
        restart: unless-stopped
        volumes:
            - mysql_data_dev:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: library
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"  # 開発環境用MySQLポート
        networks:
            - library-dev-network
    
    redis:
        image: redis:7-alpine
        container_name: library-dev-redis
        restart: unless-stopped
        ports:
            - "6380:6379"  # 開発環境用Redisポート（本番と分離）
        volumes:
            - redis_data_dev:/data
        command: redis-server --appendonly yes
        networks:
            - library-dev-network
    
    nginx:
        image: nginx:alpine
        container_name: library-dev-nginx
        restart: unless-stopped
        ports:
            - "8001:8000"  # HTTP
            - "8443:8443"  # HTTPS
        volumes:
            - ./docker/nginx/default.dev.conf:/etc/nginx/conf.d/default.conf
            - ./docker/ssl:/etc/nginx/ssl
            - .:/workdir
        depends_on:
            - app
        networks:
            - library-dev-network

    mailpit:
        image: axllent/mailpit
        container_name: library-dev-mailpit
        restart: unless-stopped
        ports:
            - "1026:1025"  # SMTP（本番と分離）
            - "8026:8025"  # Web UI（本番と分離）
        networks:
            - library-dev-network

volumes:
    mysql_data_dev:
        driver: local
    redis_data_dev:
        driver: local

networks:
    library-dev-network:
        driver: bridge
