import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            colors: {
                // Library System Colors (lib- prefix)
                'lib-primary': {
                    DEFAULT: '#3D7CA3',
                    hover: '#2A5A7A',
                    light: '#E6F0F7',
                    50: '#F0F7FF',
                    100: '#E6F0F7',
                    500: '#3D7CA3',
                    600: '#2A5A7A',
                    900: '#1A2E3A',
                },
                'lib-secondary': {
                    DEFAULT: '#669C6F',
                    hover: '#4A7A4F',
                    light: '#E8F2E9',
                    50: '#F0F9F1',
                    100: '#E8F2E9',
                    500: '#669C6F',
                    600: '#4A7A4F',
                    900: '#2A3A2F',
                },
                'lib-accent': {
                    DEFAULT: '#E3595B',
                    hover: '#C4434B',
                    light: '#F8E6E7',
                    50: '#FDF2F2',
                    100: '#F8E6E7',
                    500: '#E3595B',
                    600: '#C4434B',
                    900: '#7A2B2D',
                },
                // Semantic Colors (using lib- prefix)
                'lib-success': '#669C6F',
                'lib-error': '#E3595B',
                'lib-warning': '#F59E0B',
                'lib-info': '#3D7CA3',

                // Text colors for lib system
                'lib-text': {
                    primary: '#4f4f4f',
                    secondary: '#6b7280',
                    light: '#9ca3af',
                },

                // Legacy colors (for backward compatibility)
                primary: '#3D7CA3',
                secondary: '#669C6F',
                danger: '#E3595B',
                success: '#669C6F',
                'primary-hover': '#2A5A7A',
                'success-hover': '#4A7A4F',
                'danger-hover': '#C4434B',
                background: '#f8f9fa',
                'header-bg': '#ffffff',
                'text-primary': '#4f4f4f',
                'text-secondary': '#6b7280',
                'text-light': '#9ca3af',
                'text-white': '#ffffff',
            },
            fontFamily: {
                sans: ['Figtree', ...defaultTheme.fontFamily.sans],
            },
        },
    },

    plugins: [forms],

    // セーフリスト（Purgeで削除されないクラス）
    safelist: [
        'bg-lib-primary',
        'bg-lib-secondary',
        'bg-lib-accent',
        'text-lib-primary',
        'text-lib-secondary',
        'text-lib-accent',
        'text-lib-success',
        'text-lib-error',
        'text-lib-warning',
        'text-lib-info',
        'border-lib-primary',
        'border-lib-secondary',
        'border-lib-accent',
        'hover:bg-lib-primary-hover',
        'hover:bg-lib-secondary-hover',
        'hover:bg-lib-accent-hover',
        'focus:ring-lib-primary',
        'focus:ring-lib-secondary',
        'focus:ring-lib-accent',
        'bg-lib-primary-light',
        'bg-lib-secondary-light',
        'bg-lib-accent-light',
        'text-lib-text-primary',
        'text-lib-text-secondary',
        'text-lib-text-light',
        // アクセシビリティ関連のクラス
        'text-lib-primary-900',
        'text-lib-secondary-900',
        'text-lib-accent-900',
        'ring-lib-primary/20',
        'ring-lib-secondary/20',
        'ring-lib-accent/20',
        'focus:ring-2',
        'focus:ring-offset-2',
        'focus:outline-none',
        'sr-only',
        // 統一されたコンポーネントクラス
        'btn-primary',
        'btn-secondary',
        'btn-danger',
        'btn-outline-primary',
        'btn-outline-secondary',
        'btn-outline-danger',
        'btn-ghost',
        'btn-sm',
        'btn-lg',
        'btn-xl',
        'card',
        'card-elevated',
        'card-outlined',
        'card-header',
        'card-body',
        'card-footer',
        'alert',
        'alert-success',
        'alert-error',
        'alert-warning',
        'alert-info',
        'form-input',
        'form-input-error',
        'form-label',
        'form-help',
        'form-error',
        'status-available',
        'status-borrowed',
        'status-processing',
        'link-primary',
        'link-secondary',
        'table',
        'table-header',
        'table-header-cell',
        'table-body',
        'table-cell',
    ],
};
